keepEmptyPriority: false
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
lists:
  - hidden: false
    name: NOTE
  - hidden: false
    name: TODO
  - hidden: false
    name: DOING
  - hidden: false
    ignore: true
    name: DONE
settings:
  openIn: code
  customOpenIn: ""
  editorTheme: blackboard
  journalType: Single File
  journalPath: /notes
  appendNewCardsTo: log.md
  newCardSyntax: MARKDOWN
  replaceSpacesWith: "-"
  plugins:
    devMode: false
  filteredLists: []
  journalTemplate: null
  theme: dark
  addNewCardsToTop: false
  views:
    - id: default
      filter: ""
  cards:
    colors:
      - color: red
        filter: list=DOING
      - color: green
        filter: list=NOTE
    template: |

      <!--
      created:${(new Date()).toISOString()}
      -->
    links:
      - href: >-
          https://twitter.com/intent/tweet?text=${encodedText}%0ATweeted%20with%20@imdoneio
        icon: twitter
        pack: fab
        title: Tweet this card
    trackChanges: false
    metaNewLine: false
    addCompletedMeta: false
    addCheckBoxTasks: false
    doneList: DONE
    taskPrefix: "###"
    tagPrefix: "#"
    metaSep: ":"
    maxLines: 10
    addNewCardsToTop: true
    defaultList: NOTE
